const BenefitData = (collectionData: unknown) => {
  return {
    name: 'Progressive Discount',
    type: 'progressive',
    areSalesChannelIdsExclusive: false,
    beginDate: {
      year: 2010,
      month: 1,
      date: 1,
      day: 1,
      obj: '2010-01-01T00:00:00.000Z',
      pick: 1600743600000,
    },
    offset: -3,
    newOffset: -3,
    recurrencyCrons: null,
    activeDaysOfWeek: [],
    brands: [],
    brandsAreInclusive: true,
    campaigns: [],
    categories: [],
    clusterExpressions: [],
    clusterOperator: 'all',
    categoriesAreInclusive: true,
    collections1BuyTogether: [collectionData],
    cumulative: false,
    accumulateWithManualPrice: false,
    enableBuyTogetherPerSku: false,
    description: null,
    endDate: {
      year: 2070,
      month: 1,
      date: 1,
      day: 1,
      obj: '2070-01-01T00:00:00.000Z',
      pick: 1600743600000,
    },
    isMinMaxInstallments: false,
    daysAgoOfPurchases: null,
    purchaseHistoryType: 'toFrom',
    beginDateOfPurchasesUtc: null,
    endDateOfPurchasesUtc: null,
    slasIds: [],
    isShippingCountriesSelected: false,
    isSlaSelected: false,
    idCalculatorConfiguration: null,
    idCollectionIsInclusive: true,
    collectionsIsInclusive: true,
    collections: [],
    idsSalesChannel: [],
    idSeller: null,
    idSellerIsInclusive: true,
    installment: null,
    minInstallment: null,
    maxInstallment: null,
    isActive: true,
    isArchived: false,
    isFeatured: false,
    isFirstBuy: false,
    firstBuyIsProfileOptimistic: true,
    listSku1BuyTogether: [],
    listSku2BuyTogether: [],
    maxUsage: null,
    maxUsagePerClient: null,
    maxNumberOfAffectedItems: null,
    maxNumberOfAffectedItemsGroupKey: null,
    origin: 'Marketplace',
    minimumQuantityBuyTogether: null,
    quantityToAffectBuyTogether: null,
    paymentsMethods: [],
    paymentsRules: [],
    products: [],
    affiliates: [],
    productsAreInclusive: true,
    restrictionsBins: [],
    marketingTags: [],
    utmSource: null,
    utmCampaign: null,
    utmiCampaign: null,
    totalValueFloor: null,
    totalValueCeling: null,
    totalValueMode: 'IncludeMatchedItems',
    itemMinPrice: null,
    itemMaxPrice: null,
    compareListPriceAndPrice: false,
    isDifferentListPriceAndPrice: false,
    totalValuePurchase: null,
    rebatePercentualDiscountValue: null,
    percentualDiscountValueList: [
      {
        quantity: 5,
        percent: 5,
      },
      {
        quantity: 10,
        percent: 15,
      },
      {
        quantity: 15,
        percent: 25,
      },
      {
        quantity: 20,
        percent: 35,
      },
    ],
    percentualDiscountValueList1: null,
    percentualDiscountValueList2: null,
    skusGift: {
      quantitySelectable: 1,
      gifts: [],
    },
    activateGiftsMultiplier: false,
    applyToAllShippings: false,
    zipCodeRanges: [],
    stores: [],
    storesAreInclusive: true,
    maxPricePerItem: [],
    skusMaxPrices: [],
    maxPricesPerItems: [],
    generalValues: null,
    productsSpecifications: [],
    orderStatusRewardValue: 'invoiced',
    recurrencyErrors: null,
    beginDateUtc: '2010-01-01T00:00:00.000Z',
    endDateUtc: '2070-01-01T00:00:00.000Z',
    marketingTagsAreNotInclusive: false,
    nominalDiscountValue: null,
  }
}

const TaxData = [
  {
    affiliates: [],
    name: 'ICMS',
    type: 'tax',
    areSalesChannelIdsExclusive: false,
    beginDate: {
      year: 2010,
      month: 1,
      date: 1,
      day: 2,
      obj: '2010-01-01T00:00:00.000Z',
      pick: 1598929200000,
    },
    brands: [],
    brandsAreInclusive: true,
    categories: [
      {
        id: 9284,
        name: 'Agribusiness (9284)',
      },
    ],
    clusterExpressions: [],
    clusterOperator: 'all',
    categoriesAreInclusive: true,
    collections1BuyTogether: [],
    description: null,
    endDate: {
      year: 2070,
      month: 1,
      date: 1,
      day: 4,
      obj: '2070-01-01T00:00:00.000Z',
      pick: 1662001200000,
    },
    slasIds: [],
    idCalculatorConfiguration: null,
    idCollectionIsInclusive: true,
    collectionsIsInclusive: true,
    collections: [],
    idsSalesChannel: [],
    installment: 0,
    isActive: true,
    isArchived: false,
    origin: 'Fulfillment',
    paymentsMethods: [],
    nominalTax: null,
    percentualTax: 12,
    products: [],
    productsAreInclusive: true,
    taxExpression: null,
    totalValueFloor: null,
    totalValueCeling: null,
    totalValueMode: 'IncludeMatchedItems',
    totalValuePurchase: null,
    zipCodeRanges: [],
    marketingTags: [],
    taxType: 'percentualTaxValue',
    beginDateUtc: '2020-09-01T03:00:00.000Z',
    endDateUtc: '2022-09-02T02:30:00.000Z',
    shippingPercentualTax: null,
  },
  {
    affiliates: [],
    name: 'VAT',
    type: 'tax',
    areSalesChannelIdsExclusive: false,
    beginDate: {
      year: 2010,
      month: 1,
      date: 1,
      day: 2,
      obj: '2010-01-01T00:00:00.000Z',
      pick: 1598929200000,
    },
    brands: [],
    brandsAreInclusive: true,
    categories: [
      {
        id: 9284,
        name: 'Agribusiness (9284)',
      },
    ],
    clusterExpressions: [],
    clusterOperator: 'all',
    categoriesAreInclusive: true,
    collections1BuyTogether: [],
    description: null,
    endDate: {
      year: 2070,
      month: 1,
      date: 1,
      day: 4,
      obj: '2070-01-01T00:00:00.000Z',
      pick: 1662001200000,
    },
    slasIds: [],
    idCalculatorConfiguration: null,
    idCollectionIsInclusive: true,
    collectionsIsInclusive: true,
    collections: [],
    idsSalesChannel: [],
    installment: 0,
    isActive: true,
    isArchived: false,
    origin: 'Fulfillment',
    paymentsMethods: [],
    nominalTax: null,
    percentualTax: 5,
    products: [],
    productsAreInclusive: true,
    taxExpression: null,
    totalValueFloor: null,
    totalValueCeling: null,
    totalValueMode: 'IncludeMatchedItems',
    totalValuePurchase: null,
    zipCodeRanges: [],
    marketingTags: [],
    taxType: 'percentualTaxValue',
    beginDateUtc: '2020-09-01T03:00:00.000Z',
    endDateUtc: '2022-09-02T02:30:00.000Z',
    shippingPercentualTax: null,
  },
]

export { BenefitData, TaxData }
